site_name: CommonRoad Control

theme:
  name: material
  logo: assets/commonroad_white150.png

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true
            heading_level: 3
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

nav:
  - Introduction:
    - "Introduction": index.md
    - "Concept": introduction/concept.md
    - "Architecture": introduction/classdiagram.md

  - Examples:
      - "Minimal examples": examples/minimal_examples.md
      - "Long examples": examples/long_examples.md
      - "Visualization": examples/visualization_example.md

  - Integrating your own work:
    - "Planner integration": integrate_your_own_work/planner_integration.md
    - "Controller integration": index.md
    - "Dynamics integration": index.md

  - Models and Simulation:
      - "Vehicle Dynamics": index.md
      - "Noise": index.md
      - "Disturbance": index.md
      - "Sensors": index.md

  - Easy API:
      - "PID": easy_api/easy_pid.md
      - "MPC": easy_api/easy_mpc.md

  - Core API:
      - "Control":
          - "Controller Interface": core_api/control/controller_interface.md
          - "Model Predictive Control": core_api/control/mpc.md
          - "PID": core_api/control/pid.md
          - "Reference Trajectory": core_api/control/ref_traj.md

      - "Simulation":
          - "Simulation": core_api/simulation/simulation.md
          - "Sensor Models": core_api/simulation/sensor_models.md
          - "Uncertainty Models": core_api/simulation/uncertainty_models.md

      - "Vehicle Dynamics":
          - "Interfaces": core_api/vehicle_dynamics/interfaces.md
          - "Kinematic Bicycle": core_api/vehicle_dynamics/kb.md
          - "Dynamic Bicycle": core_api/vehicle_dynamics/db.md

      - "Vehicle Parameters":
          - "Interface": core_api/vehicle_parameters/interfaces.md
          - "BMW 3": core_api/vehicle_parameters/bmw3.md

      - "Planning Converter":
          - "Interface": core_api/planning_converter/interfaces.md
          - "Reactive Planner Converter": core_api/planning_converter/reactive_planner_converter.md

      - "utils":
          - "visualization": core_api/util/visualization.md
          - "other utils": core_api/util/other_util.md






